swipe:
  3:
    left:
      command: "xdotool key alt+Right" # History forward 
    right:
      command: "xdotool key alt+Left" # History back
#    up:
#      command: "xdotool key super" # Activity
#    down:
#      command: "xdotool key super" # Activity
    up:
      command: 'xdotool key Control_L+F10' # Workspace overview
    down:
      command: 'xdotool key Shift_L+Alt_L+Tab'

  4:
    left:
      command: "xdotool key ctrl+alt+Down" # Switch to next workspace
    right:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
    up:
      command: "xdotool key ctrl+alt+Down" # Switch to next workspace
    down:
      command: "xdotool key ctrl+alt+Up" # Switch to previous workspace
pinch:
  in:
    command: "xdotool keydown ctrl click 4 keyup ctrl" # Zoom in
    threshold: 0.1
  out:
    command: "xdotool keydown ctrl click 5 keyup ctrl" # Zoom out
#    command: 'xdotool key ctrl+minus'
    threshold: 0.1

threshold:
  swipe: 0.6
  pinch: 1

interval:
  swipe: 0.6
  pinch: 1
