#!/bin/sh 
BrPath='/sys/class/backlight/intel_backlight/' 
BrCur=`cat ${BrPath}brightness` 
BrMax=`cat ${BrPath}max_brightness` 
BrMin=$(( (BrMax + (100 - 1)) / 100))   # 100th max-brightness, rounded up to nearest integer 
yad --scale --min-value $BrMin --max-value $BrMax --value $BrCur --print-partial --title 'Set Brightness' --width 300 --fixed --sticky --mouse --on-top --escape-ok --button OK | while read BrNew 
   do echo "$BrNew" > ${BrPath}brightness 
   done

